#   ______________  
#  |         .__. |  ___           _          _   ___                 _          
#  | ._-.    |  | | | _ \ ___  ___| |_  __ _ | | / __| ___  _ _ __ __(_) __  ___ 
#  |         '""' | |  _// _ \(_-<|  _|/ _` || | \__ \/ -_)| '_|\ V /| |/ _|/ -_)
#  |     -.,-_    | |_|  \___//__/ \__|\__,_||_| |___/\___||_|   \_/ |_|\__|\___|
#  |______________| 


####################
# General Settings #
####################

## PostalService requires a database to function. Currently MySQL is supported.
database:
    user: root
    password: 1234
    host: 127.0.0.1
    port: 3306
    database: someName

## World groups allow you to segregate mail. This is useful if you have worlds with different inventories 
# and you don't want players sending items across universes.
# For example, mail sent from a world in a "Survival Universe" would not be accessible from a world in a
# "PvP Universe".
# You can define as many groups as you like.
enable-world-groups: false
world-groups:
#    Survival Universe:
#      - survival_main
#      - survival_main_nether

## Here you can set certain mail types to ignore world groups and be visible in all worlds.
# For example, you may want Letters to ignore world groups so players can communicate across universes.
mail-types-ignore-world-groups:
  letter: true
  
## Worlds listed in this blacklist prevent players from running any PostalService commands.
# This includes the ability to check mail, send mail, create mailboxes, etc.
world-blacklist:
  - worldname

## Here you can enable or disable each type of mail
# PostalService has 4 mail types built-in:
#   Letters - Allows the sending of Text only messages
#   Package - Allows the sending of in-game Items
#   Payment - Allows the sending of Money/Currency (requires Vault)
#   Xp      - Allows the sending of XP points (not levels)
enabled-mail-types:
    letter: true
    package: true
    payment: true
    xp: true
     
use-uuids: true

debug-mode: true

#################
# User Settings #
#################

inbox-sizes:
    default: 50
#    permission-group: 100

unread-mail-notifications:
    on-login: true
    on-world-change: false


####################
# Mailbox Settings #
####################

enable-mailboxes: true

require-nearby-mailbox: true

mailbox-limit:
    default: 5
#    permission-group: 100


#########################
# Trading Post Settings #
#########################

enable-trading-post: true

require-same-mailbox: false

allow-cross-world-trades: false

########################################
# Dont touch please
config-version: 1.0