#   ______________  
#  |         .__. |  ___           _          _   ___                 _          
#  | ._-.    |  | | | _ \ ___  ___| |_  __ _ | | / __| ___  _ _ __ __(_) __  ___ 
#  |         '""' | |  _// _ \(_-<|  _|/ _` || | \__ \/ -_)| '_|\ V /| |/ _|/ -_)
#  |     -.,-_    | |_|  \___//__/ \__|\__,_||_| |___/\___||_|   \_/ |_|\__|\___|
#  |______________| 


####################
# General Settings #
####################

## PostalService requires a database to function. Currently MySQL is supported.
database:
    user: root
    password: 1234
    host: 127.0.0.1
    port: 3306
    database: someName

## Here you can enable or disable each type of mail
# PostalService has 4 mail types built-in:
#   Letters - Text only messages
#   Package - In-game Items
#   Payment - Money/Currency (requires Vault)
#   Xp      - XP points (not levels)
enabled-mail-types:
    letter: true
    package: true
    payment: true
    xp: true
     
use-uuids: true

debug-mode: false

##################
# World Settings #
##################

## World groups allow you to segregate mail. This is useful if you have worlds with different 
# inventories and you don't want players sending things across universes.
# For example, mail sent from a world in a "Survival Universe" would not be accessible from a 
# world in a "PvP Universe".
# You can define as many groups as you like.

enable-world-groups: false

world-groups:
#    Survival Universe:
#      - survival_main
#      - survival_main_nether
#    Some Other Group:
#      - another_world

## Here you can set certain mail types to ignore world groups and be visible in all worlds.
# For example, you may want Letters to ignore world groups so players can 
# communicate across universes but want Packages to stay within world groups so items can't be
# shared.
mail-types-that-ignore-world-groups:
#   - letter
  
## Worlds listed in this blacklist prevent players from running any PostalService commands.
# This includes the ability to check mail, send mail, create mailboxes, etc.
world-blacklist:
  - worldname

#################
# User Settings #
#################

# This is the max inbox size per permission group.
# If a permission group is undefined, the default is used.
# Be mindful in how high you set these limits, especially on larger servers.
# This feature requires Vault. If Vault is not present, the default is used
# for everyone.
inbox-limits:
    default: 50
#    permission-group: 75

# Set this to true to have players be unable to receive mail if their inbox is full.
# If set to false, once full, old mail will instead make way for new mail automatically. 
# Old mail is never deleted in this case, however, and will reappear if the player 
# deletes other mail to make room.
hard-enforce-inbox-limit: false


# Enable or disable when the unread mail notification is shown to players.
unread-mail-notifications:
    on-login: true
    on-world-change: false


####################
# Mailbox Settings #
####################

enable-mailboxes: true

require-nearby-mailbox: true

mailbox-limit:
    default: 5
#    permission-group: 10


#########################
# Trading Post Settings #
#########################

enable-trading-post: true

require-same-mailbox: false

allow-cross-world-trades: false


#########################
# Localization Settings #
#########################

date-format: "MMM d, yyyy h:mm a"

locale-tag: "en-US"

########################################
# Don't touch please
config-version: 1.0