main: com.gmail.erikbigler.postalservice.PostalService
name: PostalService
version: 1.0
author: ebiggz
description: A mail system for Bukkit servers
softdepends: [Vault]
commands:
permissions:
    postalservice.mail.send.*:
        default: false
    postalservice.mail.check:
        default: false
    postalservice.mail.read:
        default: false
    postalservice.mail.readother:
        default: false
    postalservice.mailbox.set:
        default: false
    postalservice.mailbox.remove:
        default: false
    postalservice.mailbox.removeall:
        default: false
    postalservice.mailbox.find:
        default: false
    postalservice.mailbox.setoverride:
        default: false
    postalservice.mailbox.removeother:
        default: false
    postalservice.mailbox.removeallother:
        default: false
    postalservice.overriderequiremailbox:
        default: false
    postalservice.overrideworldblacklist:
        default: false
    postalservice.update:
        default: false
    postalservice.reload:
        default: false
    postalservice.help:
        default: false
    postalservice.user:
        default: true
        children:
            postalservice.mail.send.*: true
            postalservice.mail.check: true
            postalservice.mail.read: true
            postalservice.mailbox.set: true
            postalservice.mailbox.remove: true
            postalservice.mailbox.removeall: true
            postalservice.mailbox.find: true
            postalservice.help: true
    postalservice.mod:
        default: false
        children:
            postalservice.mailbox.setoverride: true
            postalservice.mailbox.removeother: true
            postalservice.mailbox.removeallother: true
            postalservice.mail.readother: true
    postalservice.admin:
        default: false
        children:
            postalservice.update: true
            postalservice.reload: true
            postalservice.overriderequiremailbox: true
            postalservice.overrideworldblacklist: true
    postalservice.*:
        default: op

            children:

                postalservice.mod: true
                postalservice.admin: true