main: com.gmail.erikbigler.postalservice.PostalService
name: PostalService
version: 1.0.5 SNAPSHOT
author: ebiggz
description: A mail system for Bukkit servers
softdepends: [Vault,Multiverse-Core]